#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $KEYCLOAK_DB_USER WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
    CREATE DATABASE $KEYCLOAK_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB_NAME TO $KEYCLOAK_DB_USER;

    CREATE USER $ESPRESSO_DB_USER WITH PASSWORD '$ESPRESSO_DB_PASSWORD';
    CREATE DATABASE $ESPRESSO_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $ESPRESSO_DB_NAME TO $ESPRESSO_DB_USER;
EOSQL